/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package encoding.test;

public class Library {
    private final String foo = "да";

    public boolean someLibraryMethod() {
        return true;
    }
}
